- docs.html
> document how to migrate a module

- index.html
Maybe we should think about a better layout for this page? I don't know. I can't web.
> Adding link to plugins

- docs/index.md
Updated version of #22 by @igalic
> Explain and simplify the release process

- _data/tools/modulesync.json
- docs/index.md
this was done via
perl -p -i -e 's|puppet[ -]community|voxpupuli|i' * **/*
might need capitalization in some places
> more complete rename

- _posts/2016-06-08-puppet-corosync.md
> Add a link to my slides about puppet-corosync and providers development

- index.html
This really needs to become a dynamic thing but at least now they match closer to reality. It's pretty heartwarming actually seeing with how many contributors and repositories we are grwoing whereas PR numbers are going down. It's working :smile:.
> index: Update our numbers

- .travis.yml
- Gemfile
- README.md
- Rakefile
* Introduce a `Rakefile` with the necessary tasks to build/validate the
site
* Configure html-proofer to ignore links pointing to `voxpupuli.org`
* Configure Travis to use the new Rake tasks
> Fix validation issues with html-proofer

- Gemfile
- Rakefile
* Use Jekyll's built-in commands to execute appropriate actions
* Add some additional output for the all-in-one task so we can more clearly see which step is executing
> Expand Rakefile

- _posts/2016-06-10-voxpupuli-opensource-speedtrain.md
@adrienthebo wrote a blog post that's kinda related to some of the
things we talk about here, so let's link it.
> add a link to adrien's blog post

- docs/index.md
Add deprecation info to the README.md.
Clarify how release `999.999.999` works.
> Migration process improvements

- _posts/2016-08-28-elections.md
> Announcing the first elections

- _posts/2016-08-28-elections.md
> Fix number of repos

- _posts/2016-09-03-becoming-a-candidate.md
> Call for Participation in the VP elections

- _posts/2016-09-03-becoming-a-candidate.md
> Fix 2016-09-03-becoming-a-candidate.md

- _posts/2016-09-16-puppet-corosync-reaches-5.0.0.md
> Announce Puppet-Corosync 5.0.0

- docs/index.md
> fixed typo

- security/index.md
> Change from Best to Good practices ; link to gpg signing.

- _data/tools/hiera.json
- index.html
Remove static tools panel to display latest blog
posts.
> Add latest blogposts to frontpage

- _includes/footer.html
- _layouts/default.html
Provide links to mailinglist and IRC channel.
Doesn't look very good, but the information is important.
> Add footer with get in touch links

- _includes/footer.html
so we have now: mailinglist, irc and slack.
> Link also voxpupuli channel on Slack

- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
I've added rubocop to the project and fixed everything that rubocop was complaining about.
Right now there is not much for rubocop to check apart from Gemfile and Rakefile, but this is a preparation for something I'm going to work on now.
> Add rubocop and switch to latest ruby (2.4)

- .travis.yml
Our website will be able to fetch data from the github API. This
requires oauth data from our org. they are stored encrypted in this
.travis.yml. You can review the data at
https://github.com/organizations/voxpupuli/settings/applications/467418
> add secrets for oauth + reformat of travis.yml

- .travis.yml
- _plugins/github_pr_stats.rb
Because @bastelfreak was a little overzealous, here is another PR with some fixes.
> Add GitHub stats hook

- index.html
this is a manual revert of https://github.com/voxpupuli/voxpupuli.github.io/pull/94/files + update to current numbers
> fix broken variables

- _data/tools/puppet-debugger.json
- _data/tools/puppet-repl.json
This updates puppet-repl to use the new project name of puppet-debugger.
> Changes puppet-repl to puppet-debugger

- .travis.yml
- freenode.txt
We want to be an official registered freenode group. This allows us to
get custom cloaks. More information is present at
https://freenode.net/groupreg and https://freenode.net/kb/answer/cloaks
> Add freenode authentication token

- docs/index.md
Hi,
I would like to add a list of questions a reviewer can go through while checking a pull request. This list isn't complete. I would like to get this to our website as soon as possible and update it from time to time
> add basic list of review infos

- _posts/2016-06-10-voxpupuli-opensource-speedtrain.md
> propose small spelling changes

- _posts/2018-02-06-voxpupuli-community-journey.md
i hoped travis would catch this
> Fix image URLs in talk transcription

- docs/index.md
> Clarity around collab list

- docs/index.md
> Clarify that we're reviewing a module PR, not a module

- docs/index.md
This is on what we agreed on the IRC channel and the mailinglist
> ensure that the lowest puppet version is 4.10.0

- docs/index.md
This is the outcome of a discussion about https://github.com/voxpupuli/puppet-nginx/pull/1189 on the IRC.
> explain params that map to config options

- docs/index.md
again, this is the outcome of a discussion on the IRC. I would like to
get some feedback here.
> add a note about epp vs erb templates

- _includes/nav.html
- privacy-policy/index.md
Due to the nature of the EU's General Data Protection Regulation (GDPR) Rules, the community is required to maintain a Privacy Policy that is compliant with the new rules. This PR is the living draft of that new Privacy Policy and we want to give the community time to review it before we publish it officially.
@voxpupuli/collaborators Everyone please take part in reviewing and contributing to the discussion surrounding the Vox Pupuli Privacy Policy.
> Privacy policy

- index.html
- static/css/site.css
Includes some minor style changes to make it fit & look right.
> Add link to PR manager

- coc/index.md
- docs/index.md
Fixes https://github.com/voxpupuli/voxpupuli.github.io/issues/59
> update link to PMC people in our CoC

- LICENSE2
- README.md
- _includes/footer.html
- license.md
@alexjfisher @dhollinger I need some feedback here :)
> update license to CC-BY-SA 4.0

- _posts/2019-01-03-dropping-puppet4.md
@voxpupuli/collaborators I would like to get some feedback here :)
> add blogpost for puppet4 deprecation

- _data/tools/hiera.json
- plugins/index.md
I have added a 3rd row to list the hiera 5 backends.
> add hiera 5 backends

- index.html
> Link to GitHub search instead of heroku app.

- index.html
this will surface open issues on the homepage too. At least a link to
them!
> Add link to open issues

- index.html
* Repositories have contributors
* Issues are resolved by pull requests
> Change order of panels

- docs/index.md
Add a review statement about dropping operating systems for a module.
> mention OS bumps

- README.md
- about.md
- coc/index.md
- docs/index.md
- elections/index.md
Fixed issues in several markdown files that were detected by https://github.com/markdownlint/markdownlint
> Fix markdown styling in multiple files

- docs/index.md
> update docs for data-in-modules

- static/css/site.css
> ensures that the breadcrumb is on the next line

- _docs/migrate_module.md
Seems like those links gone missing in #202.
> Add missing links

- _docs/master_agent.md
- _docs/monolithic.md
- _layouts/architecture.html
- docs/index.md
- static/css/site.css
Do not merge this as is. It's not ready to go live on the site.
You'll want to use the `Checkout via command line` instructions on the
PR to check this out locally so you can tweak the graph and see it live.
Check out the PR, run the site locally with `jekyll serve`, tweak and
improve as needed.
It's a reasonable example, for sure, but the purpose of this PR is
simply to create the framework and demonstrate an example so that
you can more easily put together the reference yourself.
See https://mermaidjs.github.io/#/flowchart for syntax documentation.
Also, if anyone knows of a better text based chart DSL, then please suggest.
> The start of a set of reference architectures

- privacy-policy/index.md
> privacy-policy/index.md: fix email link

- _docs/releasing_version.md
* Now mentions gpg
* Properly explains our changelog generator
> Update module release docs

- Gemfile
- README.md
- _config.yml
- _layouts/post.html
tested this locally with `bundle exec rake test && cd _site && python -m http.server 8082`
> Add `last modified at` to posts

- _docs/migrate_module.md
Updates to migration documentation for a github actions world
> Update migration for a github actions world

- _docs/migrate_module.md
We enable `Automatically delete head branches` since a long time so we
should also document it.
> document that we delete merged branches

- _docs/pql_queries.md
I have notes to myself about which endpoints are available which I find useful. Feel free to discard any tip that isn't useful. I also wasn't sure on ordering of the extra info about endpoints and fields.
> Additional queries and general endpoint info

- _docs/pql_queries.md
I need to say that I just broke my ruby and couldn't test this locally. If you want to take a look:
bundle install --path .vendor/
bundle exec rake test
check `_site/docs/pql_queries/index.html`
> PQL overview: Implement a ToC

- _docs/pql_queries.md
And a couple of other minor [markdownlint](https://github.com/DavidAnson/markdownlint) fixes.
> pql_queries: add languages to code blocks

- _config.yml
- sponsoring/index.md
@bastelfreak asked me for a sponsoring page, so this is my start for this. 
i'm open for input to make it better
> Add page with sponsoring text

- _docs/how_to_run_tests.md
Follow-up of:
https://github.com/voxpupuli/beaker-rspec/pull/117
The old names or still supported but for consistency change them to the
new ones.
> Use UPPERCASED beaker environment variable

- _docs/releasing_version.md
i stumbled upon this while doing my first releases and thought it could be good to know what you do where.
also i generalized when to do a major bump and remove the ruby1.8 reference
> update and clarify what has to be done where

- _posts/2023-04-28-drop-puppet-6.md
- _posts/2023-06-09-module-deprecation.md
- _posts/2023-07-01-stdlib-9.md
- _posts/2023-07-02-puppet-8.md
- _posts/2023-07-20-voxpupuli-sponsoring.md
- _posts/2023-08-13-github-2fa.md
- _posts/2023-08-14-module-migration.md
The preview is at https://voxpupuli.org/posts/ and uses the first praragraph of each article.
> cleanup blogposts to provide a better preview

- _docs/arch_load_balanced.md
- _docs/arch_single_server.md
- Update grafic
- add haproxy information
- update puppetserver module
> Update large arch description

- _docs/how_to_run_tests.md
I find I need this pointer every so often.
> docs/how to run tests: Add snippet for generating REFERENCE.md

- _includes/breadcrumbs.html
- _includes/head.html
- _includes/nav.html
- _includes/scripts.html
- _layouts/default.html
- _layouts/page.html
- index.html
- plugins/index.md
- sponsoring/index.md
Did not found a bootstrap 5 material design which is not mdbootstrap
> Upgrade to bootstrap 5 and remove material design

- _posts/2024-02-16-what-it-means-to-be-a-pmc-member.md
The text is not final. Please say what you think about it. Is this what you wanted to see @binford2k? (as discussed in february monthly 2024)
i wrote the base text and enhanced it through chatGPT. (because me english not best 😉 )
> Blog post about what it means to be a PMC member

- _includes/nav.html
The current menu item is not properly highlighted.  It looks like the "active" class must be set on the link, not the list item.
> Fix active menu item display

- _includes/nav.html
The mobile navbar was broken, this will fix it
> Fix mobile navigation

- _config.yml
- contributing/index.md
is the page title okay? or should i use just "Contribute"?
> Add info to webpage how to get in touch

- _posts/2024-05-08-CentOS-7-CentOS-Stream-8-deprecation.md
Followup of https://github.com/voxpupuli/voxpupuli.github.io/pull/369/
> Clarify EL8 deprecation/testing

- _posts/2024-05-08-pmc-elections-voting-period-reminder.md
the post preview at https://voxpupuli.org/blog/ displays the first paragraph. So starting with `Hi!\n` makes it look a bit stupid.
> Election post: adjust first paragraph

- _docs/releasing_version.md
Show that the person merging a release is also obligated to the final release tasks.
> Update releasing version documentation

- elections/index.md
Remove broken link to Contributor Summit page
> Remove broken link

- _posts/2025-01-05-conference-funding.md
Vox Pupuli would like to sponsor trips for some community members that want to attend config management camp.
> Add blogpost about cfg mgmtcamp sponsoring

- _docs/migrate_module.md
- static/css/site.css
This makes a clean markdown list to copy/paste with the checkboxes that github issues can handle.  It rewrites some of the entries to be shorter to make it less complex to read, while linking back to the website for reference material.
Also change some css properties to make code blocks look better.
> Add a checklist for module migration

- _docs/pql_queries.md
Took me a bit to figure out how to do this one, so might as well add it to this page.
> pql_queries: add "get nodes with fact in a list"

- _support/enterprise-modules.md
> Add enterprisemodules support to website

- openvox/install.md
This is from Slack, but I have not personally tested
> Add openvox pp yum install

- _includes/sync.md
- contributing/voxpupuli-monthly-sync.ics
@margaret-lee has provided us a new zoom link that should be stable.
> Update zoom link

- _docs/arch_single_server.md
> Architecture: document firewalling

- _posts/2025-05-15-usbguard-migration.md
Migration to Vox Pupuli: https://github.com/voxpupuli/puppet-usbguard/issues/1
> Add blogpost about usbguard migration

- _config.yml
- static/css/site.css
- voxconf.md
This looks all right at a desktop resolution, but the info overlay
floats around quite a bit as resolution changes, so it needs a bit of
work still.
I'd love it if someone with a bit more time picked this up and finished it!
> Rough draft of new voxconf page

- _docs/arch_single_server.md
> Enhance single server architecture with monitoring

- openvox/install.md
Note that this is untested; I just found the syntax error
> Fix missing comma in YUM example

- voxconf.md
not beautiful, but my css/html "skills" are close to zero.
> VoxConf: Add conference talks

- voxconf.md
> Add table class

- _docs/how_to_run_tests.md
* Expand acceptance/beaker instructions
* Remove date as it's not related to last edit
> docs: update test running instructions

- _docs/creating-new-container-repo.md
This is roughly more like a draft. To write down, what may be only my knwoledge at the moment. Please feel free to add or extend things :)
> docs: how to create a new container repo

- _includes/sync.md
this was intended for the last PR.
> forgot to update title

- voxconf.md
Robert introduced the same for our IRC list: 6923fa85dda5d54f63365ad1ec81eb5cce95ee0b
> voxconf: make table more beautiful

- _sponsors/geant.md
- _sponsors/microsoft.md
- _sponsors/puppet.md
- sponsoring/index.md
I made the one-time sponsor cards a bit smaller, but I'm not sure about
that. We can bump them up in size if people have opinions here.
> Create another tier for one-time sponsors

- _includes/connect_groups_io.md
- _includes/connect_irc.md
- _includes/connect_slack.md
- _includes/connect_social.md
- _includes/sync.md
- connect.md
- static/css/site.css
Also revamped the page just a little bit, it was starting to look
crowded.
> Add social media accounts

- _docs/extending-expired-ca-cert.md
* Make case in the title consistent
* Remove the duplicated "-noout" parameter to openssl
> Style fixes
