voxpupuli/voxpupuli.github.io

- index.html
I'm not sure why we didn't have this before
> Actually link to the docs page

- coc/index.md
Version 1.4.0 has more positive language and includes examples of behaviour we'd like to see.
I've also updated it to use the working address to contact maintainers by email.
> coc: Upgrade to 1.4.0 of the Contributor Covenant

- docs/index.md
Only the minor version should be bumped if the module is pre version 1.0 and ruby 1.8 support has been dropped.
> Clarify version numbering

- _includes/nav.html
- _layouts/post-index.html
The links on the post overview page for posts we host are automatically
generated so they will never fail, we can ignore these. If we don't add
creation time the external resource won't exist yet and Travis will
register a build failure.
Similarly for links we've defined in our site navigation, if we're
addind new pages those pages aren't there yet so the tests would fail.
> Exempt internal/generated links from htmlproofer

- Rakefile
- _layouts/post.html
When I turned the HTML checker on in html-proofer it found an additional closing `h1` in the post template that shouldn't have been there.
> Fix post template

- .travis.yml
For whatever reason the old Bundler version with this version of Ruby pulls in a completely broken set of dependencies. Upgrading bundler seems to help. Travis ought to keep more up to date with this in their images.
> travis: Fix the dependency issue

- _data/tools/puppet-lint.json
useful to take advantage of the structured facts and `$facts` hash in
puppet 4 but puppet 3 users can also make use of them if they've
configured puppet correctly or are running a new version of facter
* top_scope_facts - lints for facts like `$::operatingsystem` and
replaces them with `$facts['operatingsystem']` .
* legacy_facts - lints for so called legacy facts like
`$facts['operatingsystemmajrelease']` or `$::operatingsystemmajrelease`
and replaces them with the new fancy structured fact like
`$facts['os']['release']['major']`
ref https://github.com/voxpupuli/plumbing/issues/21
> add top_scope_facts and legacy_facts linters

- _posts/2017-01-11-migrating-to-puppet4.md
older version ship also an older rubocop conf. This will fail on travis
> add note about needed modulesync

- _posts/2017-01-11-migrating-to-puppet4.md
0.16.7 ships a rubocop config that doesn't work anymore
> bump required modulesync version 0.16.7 -> 0.16.8

- _data/tools/editors-IDEs.json
This commit adds entries for the VS Code and Atom IDE plugins for Puppet.
> Update editor list for VSCode and Atom

- docs/index.md
Our style is currently a bit inconsistent. Sometimes we just use a single whitespace before/after `=`, sometimes everything is aligned at =. I prosed the second way for the style guide, since that is more common in our modules.
> add a note about parameter alignment

- _includes/stats.html
This will count all pages of members, not just the first one.
Unfortunately, since this is an unauthenticated API call, it only lists
public members and so it will always be short.
> Slightly better member counting

- _config.yml
With the additional *Leadership* link in there, I'm a little concerned
that the header might be too wide. If so, we can shorten it easily by
not using the full word here.
> Shorten the header a bit

- docs/index.md
I added the link to the puppet 5.3 documentation on purpose. It nicely
describes the differences between Hiera 3 and 5 and how people can
migrate. This is probably helpful if somebody contributed hiera 3 syntax
by accident. We can than simply link to the docs mentioned in this
document.
> mention hiera5 compatibility for data-in-modules

- docs/index.md
with the newline, github pages won't render the table of contents
properly
> fix our ToC

- _data/tools/hiera.json
<https://github.com/binford2k/hiera-rest> is non-existing and returns a 404.
> Removed 404'ing hiera-rest repository

- _includes/footer.html
Without this patch, the link is relative and works on the home page and
404's everywhere else.
> (GH-195) Fix license link 404

- elections/index.md
Fixes #194
... at least in parts. This commit adds a mention to our governance
document. People that are not part of our GitHub org cannot access
teams.
> Add a notice for the PMC group

- Rakefile
This does not overwrite the default tasks anymore and automatically provides the rubocop:auto_correct task
> Rework rubocop task handling

- _docs/releasing_version.md
@bastelfreak suggested on my last release PR for puppet-prometheus to regenerate the Puppet Strings documentation because it was outdated. I think this is a good thing to do on all releases and should therefore be mentioned in our documentation.
> Run Puppet Strings before releasing a new version

- elections/index.md
Fix link to Puppet Contributor Summit. http://pup.pt/cso results in a 404.
> elections/index.md: fix link to Puppet Contributor Summit

- _docs/reviewing_pr.md
This change is being proposed since most repositories are moving away from Travis CI. In the one spot where a specific provider makes sense to reference, the change is from `Travis-CI` to `GitHub Actions`. In the other places it generalizes the reference by simply saying `CI`.
> Replace references to Travis

- _docs/migrate_module.md
we don't do that since a long time anymore, because the forge finally
has a deprecation feature. that's used instead and contains a notice.
> dont advise people to release in the old namespace

- _docs/updating-files-managed-with-modulesync.md
Feel free to contribute to this PR by adding commits :-)
> Add a help page for updating files managed with modulesync

- freenode.txt
this was used to authorize our project on freenode. it's not required anymore.
> delete legacy freenode file

- .rubocop.yml
- Gemfile
We already lint for ruby 3.0 so it doesn't make sense to depend on the
EoL rubocop versions.
> rubocop: Allow latest versions

- _docs/pql_queries.md
> PQL docs: fix codeblock syntax

- security/index.md
our modules should not link to the security section. we've the security policy defined on our org level.
> Cleanup the security section

- sponsoring/index.md
for the 50$/month tier sponsors can get their logo on our website.
> sponsoring: Add hetzner cloud logo

- _docs/migrate_module.md
This is already told a few lines above and the person who transfer the repository, as an owner, should be able to do it, so keep that one instead.
> Remove duplicate instruction

- _posts/2023-04-28-drop-puppet-6.md
- _posts/2023-06-09-module-deprecation.md
- _posts/2023-07-01-stdlib-9.md
- _posts/2023-07-02-puppet-8.md
- _posts/2023-07-20-voxpupuli-sponsoring.md
- _posts/2023-08-13-github-2fa.md
- _posts/2023-08-14-module-migration.md
The idea is to release a short blog post from time to time to inform people about changes within Vox Pupuli or our code base. I added a few posts for previous events in this year.
> Add a series of short blog posts

- _docs/deprecated_and_archived_modules.md
This file was removed from the repository in https://github.com/voxpupuli/plumbing/commit/83482a85983901d80e2e440951323e7114d498bf
> deprecation: remove plumbing step

- .github/workflows/post_to_dev_to.yml
- .gitignore
- _posts/2024-02-16-we-are-now-on-dev-to.md
- add blog post about dev.to
- add and test action to cross-post to dev.to
- update gitignore
> Add  Blog post about dev.to and add action to automatically x-post there

- _docs/migrate_module.md
The FORGE team now uses github issues and not jira anymore. This commit updates the link to their board. We need to to ask for deprecation of the old releases.
> module migration: Add link for new FORGE project

- _includes/edit_button.html
- _layouts/architecture.html
- _layouts/page.html
- _layouts/post.html
The button style is not consistent accross pages, so move the button in its own include file and rely on it where applicable.
> Fix edit button consistency

- Gemfile
- _config.yml
- blog/index.md
Blog posts are under /blog/... but the blog index is under /posts/, as a
consequence the "Blog" button is not shown as active when a blog post is
shown.
Setup a redirect so that the old URI does not break, and relocate the
blog index in /blog/.
> Fix root uri of the blog

- _docs/pql_queries.md
The YAML had extra indentation.
> pql_queries: fix prometheus example formatting

- _docs/deprecated_and_archived_modules.md
In the past we used email threads to discuss if we want to deprecate/archive a module. I think this is fine, so this should be documented on our website.
> module deprecation: Allow deprecation-discussion on mailinglist

- _posts/2024-07-26-module-deprecation.md
This follows an anouncement from out mailinglist. We deprecate
* puppet-dropbear
* puppet-etherpad
* puppet-ghost
* puppet-jenkins_job_builder
* puppet-pxe
Related modulesync_config PR: https://github.com/voxpupuli/modulesync_config/pull/919
> Deprecate multiple modules

- _docs/releasing_version.md
I think the original wording was a bit unclear. One could read it as:
Run those commands:
```
git switch -c <branch>
git add <file(s)>
git commit
git push local <branch>
```
Then update the changelog.
That doesn't make sense.
> Rework our release documentation

- _posts/2024-10-01-debian-11.md
In the past we agreed on not supporting Debian LTS versions, only the standard versions (and I know that I was one of the people that pushed for not supported LTS back then). Debian 11 switched from standard to LTS on 2024-08-15. There are still requests from users to support Debian 11 and I think with the slow response from Puppet about new debian packages it makes sense to reconsider it.
Please respond with :+1: if you agree or with :-1: if you think we shouldn't support the LTS versions. When we've some feedback we can merge this PR or close it.
> Consider Debian LTS as supported

- _includes/footer.html
- _includes/nav.html
This is just the raw invite link at this point. As soon as @bastelfreak
gets the shortlink updated, we'll replace it.
Tangent: we should simplify the nav header soon!
> Add icon and invite to new slack

- coc/index.md
We use the code of conduct from https://www.contributor-covenant.org/. This PR updates our old version of 1.4 to 2.1.
I tried to keep the diff as readable as possible and ignored markdown linting to make reviewing it easier. This is a direct copy of https://www.contributor-covenant.org/version/2/1/code_of_conduct/ with one exception. We previously had:
```
Our maintainers are elected on a yearly basis as the project management
committee. You can find an up to date list of those people [on our site][pmc]
```
in the `Enforcement Responsibilities` section. I kept it.
> Code of conduct: Update version 1.4 -> 2.1

- _config.yml
- _includes/footer.html
- _includes/github-repo-search.html
- _includes/head.html
- _includes/nav.html
- connect.md
- plugins/index.md
- projects.md
- static/css/site.css
This takes the very busy navigation bars and reorganizes them into
dropdown menus. This gives us a lot more open space, but also lets have
a more intuitive navigation structure.
- moves the "connect with us" links from the footer into a nav menu.
- also creates a `/connect` page that better explains what's bridged
and how you can choose protocols to connect with.
- adds a Project Overview page with links to github repo lists
- configures the entire nav structure in `_config.yml` instead of some
being hardcoded in the html
- adds the ability to add icons to any menu item.
- if the icons aren't appreciated, just delete from the config
- updated to current FontAwesome so the online search is usable
I did -not- make the money icon spin around, but I was tempted to.
If you like the overall …
> revamps navigation menus by adding dropdowns

- static/css/site.css
The dropdown looks great on full size, but when we switch to the mobile
view, the unstyled list actually looks better. This breakpoint matches
the `navbar-expand-lg` parent class, so if that's changed, then this
should change to match. See https://getbootstrap.com/docs/5.0/layout/breakpoints/#available-breakpoints
Note that this will be easier to review if you set to ignore whitespace. All this does is add a breakpoint and indent some code to match.
> use the unstyled menu list on mobile

- README.md
- _docs/about_vox_pupuli.md
- connect.md
- contributing/index.md
- docs/index.md
This aims to make the chat URLs more consistent. The Slack links still aren't quite consistent, but I don't know exactly how that's supposed to work. See individual commit for details.
> Consistent communication links

- contributing/index.md
If the current month meeting has started 1h ago or more (and not is
going to start in less that one hour), it is over, and we wnat to move
to the next month.
> Fix when we show next month meeting

- openvox/install.md
The `openvox-server` and `openvox-db` packages haven't been published
yet, but they should be very shortly.
> Update the install instructions for the new packages

- _data/tools/editors-IDEs.json
From https://marketplace.visualstudio.com/items?itemName=jpogran.puppet-vscode
> We are proud to announce that Official Puppet VS Code Extension is moving to the Puppetlabs namespace in the VS Code Marketplace!
> [docs] update url for vscode

- _docs/releasing_version.md
- _posts/2025-02-04-new-release-workflow.md
It's now possible that GitHub generates the whole release PR for us.
This requries:
* https://github.com/voxpupuli/gha-puppet/pull/66
* https://github.com/voxpupuli/modulesync_config/pull/943
> Document new release workflow & add blogpost about it

- _posts/2025-02-04-new-release-workflow.md
I was wondering why I didn't see the post in the RSS feed.
> blogpost: Fix date 2024-02-04->2025-02-04

- _docs/migrate_module.md
Back in the day the incoming-migrations team had permissions to create
repositories, which allowed migrations. These days GitHub no longer has
team specific repo-create permission and it's a global setting.
> Remove outdated incoming-migrations team reference

- _docs/pql_queries.md
Could not find an example of doing this. I could not find a way to filter arrays of structured facts with PQL, so had to use `jq`.
> pql_queries: add "get nodes with specific array element value in a fact"

- .github/workflows/test.yml
the action only works when the base branch is in the Vox Pupuli org.
> Use sticky PR comment only for branches from origin

- _docs/software_support_lifecycle.md
Prior to this, it was very difficult to determine where one heading stopped and the next column started. By center-aligning that issue is solved.
> Reformatted table, fixed markdown lint errors

- .github/workflows/test.yml
The step doesn't work when the PR was raised from a fork.
> Disable posting a comment to PRs

- openvox/vpat.md
See https://en.wikipedia.org/wiki/Voluntary_Product_Accessibility_Template
for information about the VPAT standard.
This describes the accessibility features of OpenVox. It does -NOT- add
it to the navigation menu at this time, so the URL will need to be
shared directly with users who require it. We can figure out later how
we want to display or link to this.
The link will be http://voxpupuli.org/openvox/vpat/
> Adds a basic VPAT document

- openvox/install.md
- static/css/site.css
The install page was starting to look a lot more complex than it had to
be. This simply focuses on the "easy path" and moves everything else down
to an "advanced" section.
> Simplify the install page

- static/css/site.css
our theme "resets" everything, so without adding it back, the quote
styling looks no different from body text.
> Add quote styling back

- voxconf.md
This message was to ensure that people saw that there was more info on the page, like the travel budget and the cfp and whatnot.
> add 'more info' message back

- _includes/sync.md
- contributing/voxpupuli-monthly-sync.ics
We've decided to center Vox Pupuli, so we're switching the meeting link
to one managed by Vox Pupuli PMC.
> Updating the sync link to Vox managed

- _includes/connect_irc.md
The SIG was formed yesterday:
https://github.com/voxpupuli/community-triage/wiki/SIG.OpenBolt
> Add sig-openbolt channels

- _docs/how_to_run_tests.md
Reference: https://github.com/voxpupuli/voxpupuli-acceptance/blob/master/CHANGELOG.md#400-2025-08-11
> how to run tests: need ruby 3.2+ as of voxpupuli-acceptance 4.0.0
